/**
 * This file was automatically generated by @algorandfoundation/algokit-client-generator.
 * DO NOT MODIFY IT BY HAND.
 * requires: @algorandfoundation/algokit-utils: ^7
 */
import { AlgorandClientInterface } from '@algorandfoundation/algokit-utils/types/algorand-client-interface';
import { ABIReturn } from '@algorandfoundation/algokit-utils/types/app';
import { Arc56Contract } from '@algorandfoundation/algokit-utils/types/app-arc56';
import { AppClient as _AppClient, AppClientMethodCallParams, AppClientParams, AppClientBareCallParams, CallOnComplete, AppClientCompilationParams, ResolveAppClientByCreatorAndName, ResolveAppClientByNetwork, CloneAppClientParams } from '@algorandfoundation/algokit-utils/types/app-client';
import { AppFactory as _AppFactory, AppFactoryAppClientParams, AppFactoryResolveAppClientByCreatorAndNameParams, AppFactoryDeployParams, AppFactoryParams, CreateSchema } from '@algorandfoundation/algokit-utils/types/app-factory';
import { TransactionComposer, AppCallMethodCall, AppMethodCallTransactionArgument, RawSimulateOptions, SkipSignaturesSimulateOptions } from '@algorandfoundation/algokit-utils/types/composer';
import { SendParams, SendAtomicTransactionComposerResults } from '@algorandfoundation/algokit-utils/types/transaction';
import { modelsv2, OnApplicationComplete, Transaction, TransactionSigner } from 'algosdk';
import SimulateResponse = modelsv2.SimulateResponse;
export declare const APP_SPEC: Arc56Contract;
/**
 * A state record containing binary data
 */
export interface BinaryState {
    /**
     * Gets the state value as a Uint8Array
     */
    asByteArray(): Uint8Array | undefined;
    /**
     * Gets the state value as a string
     */
    asString(): string | undefined;
}
/**
 * Expands types for IntelliSense so they are more human readable
 * See https://stackoverflow.com/a/69288824
 */
export type Expand<T> = T extends (...args: infer A) => infer R ? (...args: Expand<A>) => Expand<R> : T extends infer O ? {
    [K in keyof O]: O[K];
} : never;
/**
 * The argument types for the Council contract
 */
export type CouncilArgs = {
    /**
     * The object representation of the arguments for each method
     */
    obj: {
        'create(uint64)void': {
            /**
             * The application ID of the XGovRegistry contract.
             */
            registryId: bigint | number;
        };
        'update_council()void': Record<string, never>;
        'add_member(address)void': {
            /**
             * The address of the member to add.
             */
            address: string;
        };
        'remove_member(address)void': {
            /**
             * The address of the member to remove.
             */
            address: string;
        };
        'vote(uint64,bool)void': {
            /**
             * The ID of the proposal to vote on.
             */
            proposalId: bigint | number;
            /**
             * Whether or not to block the proposal.
             */
            block: boolean;
        };
        'op_up()void': Record<string, never>;
    };
    /**
     * The tuple representation of the arguments for each method
     */
    tuple: {
        'create(uint64)void': [registryId: bigint | number];
        'update_council()void': [];
        'add_member(address)void': [address: string];
        'remove_member(address)void': [address: string];
        'vote(uint64,bool)void': [proposalId: bigint | number, block: boolean];
        'op_up()void': [];
    };
};
/**
 * The return type for each method
 */
export type CouncilReturns = {
    'create(uint64)void': void;
    'update_council()void': void;
    'add_member(address)void': void;
    'remove_member(address)void': void;
    'vote(uint64,bool)void': void;
    'op_up()void': void;
};
/**
 * Defines the types of available calls and state of the Council smart contract.
 */
export type CouncilTypes = {
    /**
     * Maps method signatures / names to their argument and return types.
     */
    methods: Record<'create(uint64)void' | 'create', {
        argsObj: CouncilArgs['obj']['create(uint64)void'];
        argsTuple: CouncilArgs['tuple']['create(uint64)void'];
        returns: CouncilReturns['create(uint64)void'];
    }> & Record<'update_council()void' | 'update_council', {
        argsObj: CouncilArgs['obj']['update_council()void'];
        argsTuple: CouncilArgs['tuple']['update_council()void'];
        returns: CouncilReturns['update_council()void'];
    }> & Record<'add_member(address)void' | 'add_member', {
        argsObj: CouncilArgs['obj']['add_member(address)void'];
        argsTuple: CouncilArgs['tuple']['add_member(address)void'];
        returns: CouncilReturns['add_member(address)void'];
    }> & Record<'remove_member(address)void' | 'remove_member', {
        argsObj: CouncilArgs['obj']['remove_member(address)void'];
        argsTuple: CouncilArgs['tuple']['remove_member(address)void'];
        returns: CouncilReturns['remove_member(address)void'];
    }> & Record<'vote(uint64,bool)void' | 'vote', {
        argsObj: CouncilArgs['obj']['vote(uint64,bool)void'];
        argsTuple: CouncilArgs['tuple']['vote(uint64,bool)void'];
        returns: CouncilReturns['vote(uint64,bool)void'];
    }> & Record<'op_up()void' | 'op_up', {
        argsObj: CouncilArgs['obj']['op_up()void'];
        argsTuple: CouncilArgs['tuple']['op_up()void'];
        returns: CouncilReturns['op_up()void'];
    }>;
    /**
     * Defines the shape of the state of the application.
     */
    state: {
        global: {
            keys: {
                registryAppId: bigint;
                memberCount: bigint;
            };
            maps: {};
        };
        box: {
            keys: {};
            maps: {
                members: Map<string, Uint8Array>;
                votes: Map<bigint | number, [string, boolean][]>;
            };
        };
    };
};
/**
 * Defines the possible abi call signatures.
 */
export type CouncilSignatures = keyof CouncilTypes['methods'];
/**
 * Defines the possible abi call signatures for methods that return a non-void value.
 */
export type CouncilNonVoidMethodSignatures = keyof CouncilTypes['methods'] extends infer T ? T extends keyof CouncilTypes['methods'] ? MethodReturn<T> extends void ? never : T : never : never;
/**
 * Defines an object containing all relevant parameters for a single call to the contract.
 */
export type CallParams<TArgs> = Expand<Omit<AppClientMethodCallParams, 'method' | 'args' | 'onComplete'> & {
    /** The args for the ABI method call, either as an ordered array or an object */
    args: Expand<TArgs>;
}>;
/**
 * Maps a method signature from the Council smart contract to the method's arguments in either tuple or struct form
 */
export type MethodArgs<TSignature extends CouncilSignatures> = CouncilTypes['methods'][TSignature]['argsObj' | 'argsTuple'];
/**
 * Maps a method signature from the Council smart contract to the method's return type
 */
export type MethodReturn<TSignature extends CouncilSignatures> = CouncilTypes['methods'][TSignature]['returns'];
/**
 * Defines the shape of the keyed global state of the application.
 */
export type GlobalKeysState = CouncilTypes['state']['global']['keys'];
/**
 * Defines the shape of the keyed box state of the application.
 */
export type BoxKeysState = CouncilTypes['state']['box']['keys'];
/**
 * Defines supported create method params for this smart contract
 */
export type CouncilCreateCallParams = Expand<CallParams<CouncilArgs['obj']['create(uint64)void'] | CouncilArgs['tuple']['create(uint64)void']> & {
    method: 'create';
} & {
    onComplete?: OnApplicationComplete.NoOpOC;
} & CreateSchema> | Expand<CallParams<CouncilArgs['obj']['create(uint64)void'] | CouncilArgs['tuple']['create(uint64)void']> & {
    method: 'create(uint64)void';
} & {
    onComplete?: OnApplicationComplete.NoOpOC;
} & CreateSchema>;
/**
 * Defines supported update method params for this smart contract
 */
export type CouncilUpdateCallParams = Expand<CallParams<CouncilArgs['obj']['update_council()void'] | CouncilArgs['tuple']['update_council()void']> & {
    method: 'update_council';
}> | Expand<CallParams<CouncilArgs['obj']['update_council()void'] | CouncilArgs['tuple']['update_council()void']> & {
    method: 'update_council()void';
}>;
/**
 * Defines arguments required for the deploy method.
 */
export type CouncilDeployParams = Expand<Omit<AppFactoryDeployParams, 'createParams' | 'updateParams' | 'deleteParams'> & {
    /**
     * Create transaction parameters to use if a create needs to be issued as part of deployment; use `method` to define ABI call (if available) or leave out for a bare call (if available)
     */
    createParams?: CouncilCreateCallParams;
    /**
     * Update transaction parameters to use if a create needs to be issued as part of deployment; use `method` to define ABI call (if available) or leave out for a bare call (if available)
     */
    updateParams?: CouncilUpdateCallParams;
}>;
/**
 * Exposes methods for constructing `AppClient` params objects for ABI calls to the Council smart contract
 */
export declare abstract class CouncilParamsFactory {
    /**
     * Gets available create ABI call param factories
     */
    static get create(): {
        _resolveByMethod<TParams extends CouncilCreateCallParams & {
            method: string;
        }>(params: TParams): {
            signer?: TransactionSigner | import("@algorandfoundation/algokit-utils/types/account").TransactionSignerAccount | undefined;
            rekeyTo?: string | undefined;
            note?: string | Uint8Array | undefined;
            lease?: string | Uint8Array | undefined;
            staticFee?: import("@algorandfoundation/algokit-utils/types/amount").AlgoAmount | undefined;
            extraFee?: import("@algorandfoundation/algokit-utils/types/amount").AlgoAmount | undefined;
            maxFee?: import("@algorandfoundation/algokit-utils/types/amount").AlgoAmount | undefined;
            validityWindow?: number | undefined;
            firstValidRound?: bigint | undefined;
            lastValidRound?: bigint | undefined;
            onComplete?: OnApplicationComplete | undefined;
            accountReferences?: string[] | undefined;
            appReferences?: bigint[] | undefined;
            assetReferences?: bigint[] | undefined;
            boxReferences?: (import("@algorandfoundation/algokit-utils/types/app-manager").BoxReference | import("@algorandfoundation/algokit-utils/types/app-manager").BoxIdentifier)[] | undefined;
            sender?: string | undefined;
            method: string;
            args?: (import("algosdk").ABIValue | import("@algorandfoundation/algokit-utils/types/app-arc56").ABIStruct | AppMethodCallTransactionArgument | undefined)[] | undefined;
        } & AppClientCompilationParams & {
            onComplete?: OnApplicationComplete.NoOpOC | undefined;
        };
        /**
         * Constructs create ABI call params for the Council smart contract using the create(uint64)void ABI method
         *
         * @param params Parameters for the call
         * @returns An `AppClientMethodCallParams` object for the call
         */
        create(params: CallParams<CouncilArgs['obj']['create(uint64)void'] | CouncilArgs['tuple']['create(uint64)void']> & AppClientCompilationParams & {
            onComplete?: OnApplicationComplete.NoOpOC;
        }): AppClientMethodCallParams & AppClientCompilationParams & {
            onComplete?: OnApplicationComplete.NoOpOC;
        };
    };
    /**
     * Gets available update ABI call param factories
     */
    static get update(): {
        _resolveByMethod<TParams extends CouncilUpdateCallParams & {
            method: string;
        }>(params: TParams): {
            signer?: TransactionSigner | import("@algorandfoundation/algokit-utils/types/account").TransactionSignerAccount | undefined;
            rekeyTo?: string | undefined;
            note?: string | Uint8Array | undefined;
            lease?: string | Uint8Array | undefined;
            staticFee?: import("@algorandfoundation/algokit-utils/types/amount").AlgoAmount | undefined;
            extraFee?: import("@algorandfoundation/algokit-utils/types/amount").AlgoAmount | undefined;
            maxFee?: import("@algorandfoundation/algokit-utils/types/amount").AlgoAmount | undefined;
            validityWindow?: number | undefined;
            firstValidRound?: bigint | undefined;
            lastValidRound?: bigint | undefined;
            onComplete?: OnApplicationComplete | undefined;
            accountReferences?: string[] | undefined;
            appReferences?: bigint[] | undefined;
            assetReferences?: bigint[] | undefined;
            boxReferences?: (import("@algorandfoundation/algokit-utils/types/app-manager").BoxReference | import("@algorandfoundation/algokit-utils/types/app-manager").BoxIdentifier)[] | undefined;
            sender?: string | undefined;
            method: string;
            args?: (import("algosdk").ABIValue | import("@algorandfoundation/algokit-utils/types/app-arc56").ABIStruct | AppMethodCallTransactionArgument | undefined)[] | undefined;
        } & AppClientCompilationParams;
        /**
         * Constructs update ABI call params for the Council smart contract using the update_council()void ABI method
         *
         * @param params Parameters for the call
         * @returns An `AppClientMethodCallParams` object for the call
         */
        updateCouncil(params: CallParams<CouncilArgs['obj']['update_council()void'] | CouncilArgs['tuple']['update_council()void']> & AppClientCompilationParams): AppClientMethodCallParams & AppClientCompilationParams;
    };
    /**
     * Constructs a no op call for the add_member(address)void ABI method
     *
     * Add a member to the council.
     *
     * @param params Parameters for the call
     * @returns An `AppClientMethodCallParams` object for the call
     */
    static addMember(params: CallParams<CouncilArgs['obj']['add_member(address)void'] | CouncilArgs['tuple']['add_member(address)void']> & CallOnComplete): AppClientMethodCallParams & CallOnComplete;
    /**
     * Constructs a no op call for the remove_member(address)void ABI method
     *
     * Remove a member from the council.
     *
     * @param params Parameters for the call
     * @returns An `AppClientMethodCallParams` object for the call
     */
    static removeMember(params: CallParams<CouncilArgs['obj']['remove_member(address)void'] | CouncilArgs['tuple']['remove_member(address)void']> & CallOnComplete): AppClientMethodCallParams & CallOnComplete;
    /**
     * Constructs a no op call for the vote(uint64,bool)void ABI method
     *
     * Cast a vote on a proposal.
     *
     * @param params Parameters for the call
     * @returns An `AppClientMethodCallParams` object for the call
     */
    static vote(params: CallParams<CouncilArgs['obj']['vote(uint64,bool)void'] | CouncilArgs['tuple']['vote(uint64,bool)void']> & CallOnComplete): AppClientMethodCallParams & CallOnComplete;
    /**
     * Constructs a no op call for the op_up()void ABI method
     *
     * @param params Parameters for the call
     * @returns An `AppClientMethodCallParams` object for the call
     */
    static opUp(params: CallParams<CouncilArgs['obj']['op_up()void'] | CouncilArgs['tuple']['op_up()void']> & CallOnComplete): AppClientMethodCallParams & CallOnComplete;
}
/**
 * A factory to create and deploy one or more instance of the Council smart contract and to create one or more app clients to interact with those (or other) app instances
 */
export declare class CouncilFactory {
    /**
     * The underlying `AppFactory` for when you want to have more flexibility
     */
    readonly appFactory: _AppFactory;
    /**
     * Creates a new instance of `CouncilFactory`
     *
     * @param params The parameters to initialise the app factory with
     */
    constructor(params: Omit<AppFactoryParams, 'appSpec'>);
    /** The name of the app (from the ARC-32 / ARC-56 app spec or override). */
    get appName(): string;
    /** The ARC-56 app spec being used */
    get appSpec(): Arc56Contract;
    /** A reference to the underlying `AlgorandClient` this app factory is using. */
    get algorand(): AlgorandClientInterface;
    /**
     * Returns a new `AppClient` client for an app instance of the given ID.
     *
     * Automatically populates appName, defaultSender and source maps from the factory
     * if not specified in the params.
     * @param params The parameters to create the app client
     * @returns The `AppClient`
     */
    getAppClientById(params: AppFactoryAppClientParams): CouncilClient;
    /**
     * Returns a new `AppClient` client, resolving the app by creator address and name
     * using AlgoKit app deployment semantics (i.e. looking for the app creation transaction note).
     *
     * Automatically populates appName, defaultSender and source maps from the factory
     * if not specified in the params.
     * @param params The parameters to create the app client
     * @returns The `AppClient`
     */
    getAppClientByCreatorAndName(params: AppFactoryResolveAppClientByCreatorAndNameParams): Promise<CouncilClient>;
    /**
     * Idempotently deploys the Council smart contract.
     *
     * @param params The arguments for the contract calls and any additional parameters for the call
     * @returns The deployment result
     */
    deploy(params?: CouncilDeployParams): Promise<{
        result: {
            return: import("algosdk").ABIValue | import("@algorandfoundation/algokit-utils/types/app-arc56").ABIStruct | undefined;
            deleteReturn: import("algosdk").ABIValue | import("@algorandfoundation/algokit-utils/types/app-arc56").ABIStruct | undefined;
            compiledApproval?: import("@algorandfoundation/algokit-utils/types/app").CompiledTeal | undefined;
            compiledClear?: import("@algorandfoundation/algokit-utils/types/app").CompiledTeal | undefined;
            operationPerformed: "create";
            version: string;
            name: string;
            deleted: boolean;
            createdRound: bigint;
            updatedRound: bigint;
            createdMetadata: import("@algorandfoundation/algokit-utils/types/app").AppDeployMetadata;
            deletable?: boolean | undefined;
            updatable?: boolean | undefined;
            groupId: string;
            txIds: string[];
            returns?: ABIReturn[] | undefined;
            confirmations: modelsv2.PendingTransactionResponse[];
            transactions: Transaction[];
            confirmation: modelsv2.PendingTransactionResponse;
            transaction: Transaction;
            appId: bigint;
            appAddress: string;
        } | {
            return: import("algosdk").ABIValue | import("@algorandfoundation/algokit-utils/types/app-arc56").ABIStruct | undefined;
            deleteReturn: import("algosdk").ABIValue | import("@algorandfoundation/algokit-utils/types/app-arc56").ABIStruct | undefined;
            compiledApproval?: import("@algorandfoundation/algokit-utils/types/app").CompiledTeal | undefined;
            compiledClear?: import("@algorandfoundation/algokit-utils/types/app").CompiledTeal | undefined;
            operationPerformed: "update";
            appId: bigint;
            appAddress: string;
            createdRound: bigint;
            updatedRound: bigint;
            createdMetadata: import("@algorandfoundation/algokit-utils/types/app").AppDeployMetadata;
            deleted: boolean;
            name: string;
            version: string;
            deletable?: boolean | undefined;
            updatable?: boolean | undefined;
            groupId: string;
            txIds: string[];
            returns?: ABIReturn[] | undefined;
            confirmations: modelsv2.PendingTransactionResponse[];
            transactions: Transaction[];
            confirmation: modelsv2.PendingTransactionResponse;
            transaction: Transaction;
        } | {
            return: import("algosdk").ABIValue | import("@algorandfoundation/algokit-utils/types/app-arc56").ABIStruct | undefined;
            deleteReturn: import("algosdk").ABIValue | import("@algorandfoundation/algokit-utils/types/app-arc56").ABIStruct | undefined;
            compiledApproval?: import("@algorandfoundation/algokit-utils/types/app").CompiledTeal | undefined;
            compiledClear?: import("@algorandfoundation/algokit-utils/types/app").CompiledTeal | undefined;
            operationPerformed: "replace";
            version: string;
            name: string;
            /**
             * Creates a new instance of `CouncilFactory`
             *
             * @param params The parameters to initialise the app factory with
             */
            deleted: boolean;
            createdRound: bigint;
            updatedRound: bigint;
            createdMetadata: import("@algorandfoundation/algokit-utils/types/app").AppDeployMetadata;
            deletable?: boolean | undefined;
            updatable?: boolean | undefined;
            groupId: string;
            txIds: string[];
            returns?: ABIReturn[] | undefined;
            confirmations: modelsv2.PendingTransactionResponse[];
            transactions: Transaction[];
            confirmation: modelsv2.PendingTransactionResponse;
            transaction: Transaction;
            appId: bigint;
            appAddress: string;
            deleteResult: import("@algorandfoundation/algokit-utils/types/transaction").ConfirmedTransactionResult;
        } | {
            return: import("algosdk").ABIValue | import("@algorandfoundation/algokit-utils/types/app-arc56").ABIStruct | undefined;
            deleteReturn: import("algosdk").ABIValue | import("@algorandfoundation/algokit-utils/types/app-arc56").ABIStruct | undefined;
            compiledApproval?: import("@algorandfoundation/algokit-utils/types/app").CompiledTeal | undefined;
            compiledClear?: import("@algorandfoundation/algokit-utils/types/app").CompiledTeal | undefined;
            operationPerformed: "nothing";
            appId: bigint;
            appAddress: string;
            /**
             * Returns a new `AppClient` client, resolving the app by creator address and name
             * using AlgoKit app deployment semantics (i.e. looking for the app creation transaction note).
             *
             * Automatically populates appName, defaultSender and source maps from the factory
             * if not specified in the params.
             * @param params The parameters to create the app client
             * @returns The `AppClient`
             */
            createdRound: bigint;
            updatedRound: bigint;
            createdMetadata: import("@algorandfoundation/algokit-utils/types/app").AppDeployMetadata;
            deleted: boolean;
            name: string;
            version: string;
            deletable?: boolean | undefined;
            updatable?: boolean | undefined;
        };
        appClient: CouncilClient;
    }>;
    /**
     * Get parameters to create transactions (create and deploy related calls) for the current app. A good mental model for this is that these parameters represent a deferred transaction creation.
     */
    readonly params: {
        /**
         * Gets available create methods
         */
        create: {
            /**
             * Creates a new instance of the Council smart contract using the create(uint64)void ABI method.
             *
             * Create a new council contract.
             *
             * @param params The params for the smart contract call
             * @returns The create params
             */
            create: (params: CallParams<CouncilArgs['obj']['create(uint64)void'] | CouncilArgs['tuple']['create(uint64)void']> & AppClientCompilationParams & CreateSchema & {
                onComplete?: OnApplicationComplete.NoOpOC;
            }) => Promise<{
                deployTimeParams: import("@algorandfoundation/algokit-utils/types/app").TealTemplateParams | undefined;
                schema: {
                    globalInts: number;
                    globalByteSlices: number;
                    localInts: number;
                    localByteSlices: number;
                };
                approvalProgram: Uint8Array;
                clearStateProgram: Uint8Array;
                lease?: string | Uint8Array | undefined;
                note?: string | Uint8Array | undefined;
                maxFee?: import("@algorandfoundation/algokit-utils/types/amount").AlgoAmount | undefined;
                signer?: TransactionSigner | import("@algorandfoundation/algokit-utils/types/account").TransactionSignerAccount | undefined;
                rekeyTo?: string | undefined;
                staticFee?: import("@algorandfoundation/algokit-utils/types/amount").AlgoAmount | undefined;
                extraFee?: import("@algorandfoundation/algokit-utils/types/amount").AlgoAmount | undefined;
                validityWindow?: number | undefined;
                firstValidRound?: bigint | undefined;
                lastValidRound?: bigint | undefined;
                onComplete?: OnApplicationComplete.NoOpOC | OnApplicationComplete.OptInOC | OnApplicationComplete.CloseOutOC | OnApplicationComplete.UpdateApplicationOC | OnApplicationComplete.DeleteApplicationOC | undefined;
                accountReferences?: string[] | undefined;
                appReferences?: bigint[] | undefined;
                assetReferences?: bigint[] | undefined;
                boxReferences?: (import("@algorandfoundation/algokit-utils/types/app-manager").BoxReference | import("@algorandfoundation/algokit-utils/types/app-manager").BoxIdentifier)[] | undefined;
                sender?: string | undefined;
                method: string;
                args?: (import("algosdk").ABIValue | import("@algorandfoundation/algokit-utils/types/app-arc56").ABIStruct | AppMethodCallTransactionArgument | undefined)[] | undefined;
                updatable?: boolean | undefined;
                deletable?: boolean | undefined;
                extraProgramPages?: number | undefined;
            } & {
                sender: string;
                signer: TransactionSigner | import("@algorandfoundation/algokit-utils/types/account").TransactionSignerAccount | undefined;
                method: import("@algorandfoundation/algokit-utils/types/app-arc56").Arc56Method;
                args: (import("algosdk").ABIValue | import("algosdk").TransactionWithSigner | Transaction | Promise<Transaction> | import("@algorandfoundation/algokit-utils/types/composer").AppMethodCall<import("@algorandfoundation/algokit-utils/types/composer").AppMethodCallParams> | import("@algorandfoundation/algokit-utils/types/composer").AppMethodCall<{
                    lease?: string | Uint8Array | undefined;
                    note?: string | Uint8Array | undefined;
                    maxFee?: import("@algorandfoundation/algokit-utils/types/amount").AlgoAmount | undefined;
                    args?: Uint8Array[] | undefined;
                    signer?: TransactionSigner | import("@algorandfoundation/algokit-utils/types/account").TransactionSignerAccount | undefined;
                    sender: string;
                    rekeyTo?: string | undefined;
                    staticFee?: import("@algorandfoundation/algokit-utils/types/amount").AlgoAmount | undefined;
                    extraFee?: import("@algorandfoundation/algokit-utils/types/amount").AlgoAmount | undefined;
                    validityWindow?: number | undefined;
                    firstValidRound?: bigint | undefined;
                    lastValidRound?: bigint | undefined;
                    onComplete?: OnApplicationComplete.NoOpOC | OnApplicationComplete.OptInOC | OnApplicationComplete.CloseOutOC | OnApplicationComplete.UpdateApplicationOC | OnApplicationComplete.DeleteApplicationOC | undefined;
                    accountReferences?: string[] | undefined;
                    appReferences?: bigint[] | undefined;
                    assetReferences?: bigint[] | undefined;
                    boxReferences?: (import("@algorandfoundation/algokit-utils/types/app-manager").BoxReference | import("@algorandfoundation/algokit-utils/types/app-manager").BoxIdentifier)[] | undefined;
                    approvalProgram: string | Uint8Array;
                    clearStateProgram: string | Uint8Array;
                    schema?: {
                        globalInts: number;
                        globalByteSlices: number;
                        localInts: number;
                        localByteSlices: number;
                    } | undefined;
                    extraProgramPages?: number | undefined;
                }> | import("@algorandfoundation/algokit-utils/types/composer").AppMethodCall<{
                    sender: string;
                    signer?: TransactionSigner | import("@algorandfoundation/algokit-utils/types/account").TransactionSignerAccount | undefined;
                    rekeyTo?: string | undefined;
                    note?: string | Uint8Array | undefined;
                    lease?: string | Uint8Array | undefined;
                    staticFee?: import("@algorandfoundation/algokit-utils/types/amount").AlgoAmount | undefined;
                    extraFee?: import("@algorandfoundation/algokit-utils/types/amount").AlgoAmount | undefined;
                    maxFee?: import("@algorandfoundation/algokit-utils/types/amount").AlgoAmount | undefined;
                    validityWindow?: number | undefined;
                    firstValidRound?: bigint | undefined;
                    lastValidRound?: bigint | undefined;
                    appId: bigint;
                    onComplete?: OnApplicationComplete.UpdateApplicationOC | undefined;
                    args?: Uint8Array[] | undefined;
                    accountReferences?: string[] | undefined;
                    appReferences?: bigint[] | undefined;
                    assetReferences?: bigint[] | undefined;
                    boxReferences?: (import("@algorandfoundation/algokit-utils/types/app-manager").BoxReference | import("@algorandfoundation/algokit-utils/types/app-manager").BoxIdentifier)[] | undefined;
                    approvalProgram: string | Uint8Array;
                    clearStateProgram: string | Uint8Array;
                }> | undefined)[] | undefined;
                onComplete: OnApplicationComplete.NoOpOC | OnApplicationComplete.OptInOC | OnApplicationComplete.CloseOutOC | OnApplicationComplete.UpdateApplicationOC | OnApplicationComplete.DeleteApplicationOC;
            }>;
        };
        /**
         * Gets available deployUpdate methods
         */
        deployUpdate: {
            /**
             * Updates an existing instance of the Council smart contract using the update_council()void ABI method.
             *
             * Update the council contract.
             *
             * @param params The params for the smart contract call
             * @returns The deployUpdate params
             */
            updateCouncil: (params?: CallParams<CouncilArgs['obj']['update_council()void'] | CouncilArgs['tuple']['update_council()void']> & AppClientCompilationParams) => {
                lease?: string | Uint8Array | undefined;
                note?: string | Uint8Array | undefined;
                maxFee?: import("@algorandfoundation/algokit-utils/types/amount").AlgoAmount | undefined;
                signer?: TransactionSigner | import("@algorandfoundation/algokit-utils/types/account").TransactionSignerAccount | undefined;
                rekeyTo?: string | undefined;
                staticFee?: import("@algorandfoundation/algokit-utils/types/amount").AlgoAmount | undefined;
                extraFee?: import("@algorandfoundation/algokit-utils/types/amount").AlgoAmount | undefined;
                validityWindow?: number | undefined;
                firstValidRound?: bigint | undefined;
                lastValidRound?: bigint | undefined;
                onComplete?: OnApplicationComplete | undefined;
                accountReferences?: string[] | undefined;
                appReferences?: bigint[] | undefined;
                assetReferences?: bigint[] | undefined;
                boxReferences?: (import("@algorandfoundation/algokit-utils/types/app-manager").BoxReference | import("@algorandfoundation/algokit-utils/types/app-manager").BoxIdentifier)[] | undefined;
                sender?: string | undefined;
                method: string;
                args?: (import("algosdk").ABIValue | import("@algorandfoundation/algokit-utils/types/app-arc56").ABIStruct | AppMethodCallTransactionArgument | undefined)[] | undefined;
            } & {
                sender: string;
                signer: TransactionSigner | import("@algorandfoundation/algokit-utils/types/account").TransactionSignerAccount | undefined;
                method: import("@algorandfoundation/algokit-utils/types/app-arc56").Arc56Method;
                args: (import("algosdk").ABIValue | import("algosdk").TransactionWithSigner | Transaction | Promise<Transaction> | import("@algorandfoundation/algokit-utils/types/composer").AppMethodCall<import("@algorandfoundation/algokit-utils/types/composer").AppMethodCallParams> | import("@algorandfoundation/algokit-utils/types/composer").AppMethodCall<{
                    lease?: string | Uint8Array | undefined;
                    note?: string | Uint8Array | undefined;
                    maxFee?: import("@algorandfoundation/algokit-utils/types/amount").AlgoAmount | undefined;
                    args?: Uint8Array[] | undefined;
                    signer?: TransactionSigner | import("@algorandfoundation/algokit-utils/types/account").TransactionSignerAccount | undefined;
                    sender: string;
                    rekeyTo?: string | undefined;
                    staticFee?: import("@algorandfoundation/algokit-utils/types/amount").AlgoAmount | undefined;
                    extraFee?: import("@algorandfoundation/algokit-utils/types/amount").AlgoAmount | undefined;
                    validityWindow?: number | undefined;
                    firstValidRound?: bigint | undefined;
                    lastValidRound?: bigint | undefined;
                    onComplete?: OnApplicationComplete.NoOpOC | OnApplicationComplete.OptInOC | OnApplicationComplete.CloseOutOC | OnApplicationComplete.UpdateApplicationOC | OnApplicationComplete.DeleteApplicationOC | undefined;
                    accountReferences?: string[] | undefined;
                    appReferences?: bigint[] | undefined;
                    assetReferences?: bigint[] | undefined;
                    boxReferences?: (import("@algorandfoundation/algokit-utils/types/app-manager").BoxReference | import("@algorandfoundation/algokit-utils/types/app-manager").BoxIdentifier)[] | undefined;
                    approvalProgram: string | Uint8Array;
                    clearStateProgram: string | Uint8Array;
                    schema?: {
                        globalInts: number;
                        globalByteSlices: number;
                        localInts: number;
                        localByteSlices: number;
                    } | undefined;
                    extraProgramPages?: number | undefined;
                }> | import("@algorandfoundation/algokit-utils/types/composer").AppMethodCall<{
                    sender: string;
                    signer?: TransactionSigner | import("@algorandfoundation/algokit-utils/types/account").TransactionSignerAccount | undefined;
                    rekeyTo?: string | undefined;
                    note?: string | Uint8Array | undefined;
                    lease?: string | Uint8Array | undefined;
                    staticFee?: import("@algorandfoundation/algokit-utils/types/amount").AlgoAmount | undefined;
                    extraFee?: import("@algorandfoundation/algokit-utils/types/amount").AlgoAmount | undefined;
                    maxFee?: import("@algorandfoundation/algokit-utils/types/amount").AlgoAmount | undefined;
                    validityWindow?: number | undefined;
                    firstValidRound?: bigint | undefined;
                    lastValidRound?: bigint | undefined;
                    appId: bigint;
                    onComplete?: OnApplicationComplete.UpdateApplicationOC | undefined;
                    args?: Uint8Array[] | undefined;
                    accountReferences?: string[] | undefined;
                    appReferences?: bigint[] | undefined;
                    assetReferences?: bigint[] | undefined;
                    boxReferences?: (import("@algorandfoundation/algokit-utils/types/app-manager").BoxReference | import("@algorandfoundation/algokit-utils/types/app-manager").BoxIdentifier)[] | undefined;
                    approvalProgram: string | Uint8Array;
                    clearStateProgram: string | Uint8Array;
                }> | undefined)[] | undefined;
                onComplete: OnApplicationComplete.UpdateApplicationOC;
            };
        };
    };
    /**
     * Create transactions for the current app
     */
    readonly createTransaction: {
        /**
         * Gets available create methods
         */
        create: {
            /**
             * Creates a new instance of the Council smart contract using the create(uint64)void ABI method.
             *
             * Create a new council contract.
             *
             * @param params The params for the smart contract call
             * @returns The create transaction
             */
            create: (params: CallParams<CouncilArgs['obj']['create(uint64)void'] | CouncilArgs['tuple']['create(uint64)void']> & AppClientCompilationParams & CreateSchema & {
                onComplete?: OnApplicationComplete.NoOpOC;
            }) => Promise<{
                transactions: Transaction[];
                methodCalls: Map<number, import("algosdk").ABIMethod>;
                signers: Map<number, TransactionSigner>;
            }>;
        };
    };
    /**
     * Send calls to the current app
     */
    readonly send: {
        /**
         * Gets available create methods
         */
        create: {
            /**
             * Creates a new instance of the Council smart contract using an ABI method call using the create(uint64)void ABI method.
             *
             * Create a new council contract.
             *
             * @param params The params for the smart contract call
             * @returns The create result
             */
            create: (params: CallParams<CouncilArgs['obj']['create(uint64)void'] | CouncilArgs['tuple']['create(uint64)void']> & AppClientCompilationParams & CreateSchema & SendParams & {
                onComplete?: OnApplicationComplete.NoOpOC;
            }) => Promise<{
                result: {
                    return: void | undefined;
                    compiledApproval?: import("@algorandfoundation/algokit-utils/types/app").CompiledTeal | undefined;
                    compiledClear?: import("@algorandfoundation/algokit-utils/types/app").CompiledTeal | undefined;
                    appId: bigint;
                    groupId: string;
                    txIds: string[];
                    returns?: ABIReturn[] | undefined;
                    confirmations: modelsv2.PendingTransactionResponse[];
                    transactions: Transaction[];
                    confirmation: modelsv2.PendingTransactionResponse;
                    transaction: Transaction;
                    appAddress: string;
                };
                appClient: CouncilClient;
            }>;
        };
    };
}
/**
 * A client to make calls to the Council smart contract
 */
export declare class CouncilClient {
    /**
     * The underlying `AppClient` for when you want to have more flexibility
     */
    readonly appClient: _AppClient;
    /**
     * Creates a new instance of `CouncilClient`
     *
     * @param appClient An `AppClient` instance which has been created with the Council app spec
     */
    constructor(appClient: _AppClient);
    /**
     * Creates a new instance of `CouncilClient`
     *
     * @param params The parameters to initialise the app client with
     */
    constructor(params: Omit<AppClientParams, 'appSpec'>);
    /**
     * Checks for decode errors on the given return value and maps the return value to the return type for the given method
     * @returns The typed return value or undefined if there was no value
     */
    decodeReturnValue<TSignature extends CouncilNonVoidMethodSignatures>(method: TSignature, returnValue: ABIReturn | undefined): undefined;
    /**
     * Returns a new `CouncilClient` client, resolving the app by creator address and name
     * using AlgoKit app deployment semantics (i.e. looking for the app creation transaction note).
     * @param params The parameters to create the app client
     */
    static fromCreatorAndName(params: Omit<ResolveAppClientByCreatorAndName, 'appSpec'>): Promise<CouncilClient>;
    /**
     * Returns an `CouncilClient` instance for the current network based on
     * pre-determined network-specific app IDs specified in the ARC-56 app spec.
     *
     * If no IDs are in the app spec or the network isn't recognised, an error is thrown.
     * @param params The parameters to create the app client
     */
    static fromNetwork(params: Omit<ResolveAppClientByNetwork, 'appSpec'>): Promise<CouncilClient>;
    /** The ID of the app instance this client is linked to. */
    get appId(): bigint;
    /** The app address of the app instance this client is linked to. */
    get appAddress(): string;
    /** The name of the app. */
    get appName(): string;
    /** The ARC-56 app spec being used */
    get appSpec(): Arc56Contract;
    /** A reference to the underlying `AlgorandClient` this app client is using. */
    get algorand(): AlgorandClientInterface;
    /**
     * Get parameters to create transactions for the current app. A good mental model for this is that these parameters represent a deferred transaction creation.
     */
    readonly params: {
        /**
         * Gets available update methods
         */
        update: {
            /**
             * Updates an existing instance of the Council smart contract using the `update_council()void` ABI method.
             *
             * Update the council contract.
             *
             * @param params The params for the smart contract call
             * @returns The update params
             */
            updateCouncil: (params?: CallParams<CouncilArgs['obj']['update_council()void'] | CouncilArgs['tuple']['update_council()void']> & AppClientCompilationParams) => Promise<{
                approvalProgram: Uint8Array;
                clearStateProgram: Uint8Array;
                compiledApproval?: import("@algorandfoundation/algokit-utils/types/app").CompiledTeal | undefined;
                compiledClear?: import("@algorandfoundation/algokit-utils/types/app").CompiledTeal | undefined;
                lease?: string | Uint8Array | undefined;
                note?: string | Uint8Array | undefined;
                maxFee?: import("@algorandfoundation/algokit-utils/types/amount").AlgoAmount | undefined;
                signer?: TransactionSigner | import("@algorandfoundation/algokit-utils/types/account").TransactionSignerAccount | undefined;
                rekeyTo?: string | undefined;
                staticFee?: import("@algorandfoundation/algokit-utils/types/amount").AlgoAmount | undefined;
                extraFee?: import("@algorandfoundation/algokit-utils/types/amount").AlgoAmount | undefined;
                validityWindow?: number | undefined;
                firstValidRound?: bigint | undefined;
                lastValidRound?: bigint | undefined;
                onComplete?: OnApplicationComplete | undefined;
                accountReferences?: string[] | undefined;
                appReferences?: bigint[] | undefined;
                assetReferences?: bigint[] | undefined;
                boxReferences?: (import("@algorandfoundation/algokit-utils/types/app-manager").BoxReference | import("@algorandfoundation/algokit-utils/types/app-manager").BoxIdentifier)[] | undefined;
                sender?: string | undefined;
                method: string;
                args?: (import("algosdk").ABIValue | import("@algorandfoundation/algokit-utils/types/app-arc56").ABIStruct | AppMethodCallTransactionArgument | undefined)[] | undefined;
                deployTimeParams?: import("@algorandfoundation/algokit-utils/types/app").TealTemplateParams | undefined;
                updatable?: boolean | undefined;
                deletable?: boolean | undefined;
            } & {
                appId: bigint;
                sender: string;
                signer: TransactionSigner | import("@algorandfoundation/algokit-utils/types/account").TransactionSignerAccount | undefined;
                method: import("@algorandfoundation/algokit-utils/types/app-arc56").Arc56Method;
                onComplete: OnApplicationComplete.UpdateApplicationOC;
                args: (import("algosdk").ABIValue | import("algosdk").TransactionWithSigner | Transaction | Promise<Transaction> | import("@algorandfoundation/algokit-utils/types/composer").AppMethodCall<import("@algorandfoundation/algokit-utils/types/composer").AppMethodCallParams> | import("@algorandfoundation/algokit-utils/types/composer").AppMethodCall<{
                    lease?: string | Uint8Array | undefined;
                    note?: string | Uint8Array | undefined;
                    maxFee?: import("@algorandfoundation/algokit-utils/types/amount").AlgoAmount | undefined;
                    args?: Uint8Array[] | undefined;
                    signer?: TransactionSigner | import("@algorandfoundation/algokit-utils/types/account").TransactionSignerAccount | undefined;
                    sender: string;
                    rekeyTo?: string | undefined;
                    staticFee?: import("@algorandfoundation/algokit-utils/types/amount").AlgoAmount | undefined;
                    extraFee?: import("@algorandfoundation/algokit-utils/types/amount").AlgoAmount | undefined;
                    validityWindow?: number | undefined;
                    firstValidRound?: bigint | undefined;
                    lastValidRound?: bigint | undefined;
                    onComplete?: OnApplicationComplete.NoOpOC | OnApplicationComplete.OptInOC | OnApplicationComplete.CloseOutOC | OnApplicationComplete.UpdateApplicationOC | OnApplicationComplete.DeleteApplicationOC | undefined;
                    accountReferences?: string[] | undefined;
                    appReferences?: bigint[] | undefined;
                    assetReferences?: bigint[] | undefined;
                    boxReferences?: (import("@algorandfoundation/algokit-utils/types/app-manager").BoxReference | import("@algorandfoundation/algokit-utils/types/app-manager").BoxIdentifier)[] | undefined;
                    approvalProgram: string | Uint8Array;
                    clearStateProgram: string | Uint8Array;
                    schema?: {
                        globalInts: number;
                        globalByteSlices: number;
                        localInts: number;
                        localByteSlices: number;
                    } | undefined;
                    extraProgramPages?: number | undefined;
                }> | import("@algorandfoundation/algokit-utils/types/composer").AppMethodCall<{
                    sender: string;
                    signer?: TransactionSigner | import("@algorandfoundation/algokit-utils/types/account").TransactionSignerAccount | undefined;
                    rekeyTo?: string | undefined;
                    note?: string | Uint8Array | undefined;
                    lease?: string | Uint8Array | undefined;
                    staticFee?: import("@algorandfoundation/algokit-utils/types/amount").AlgoAmount | undefined;
                    extraFee?: import("@algorandfoundation/algokit-utils/types/amount").AlgoAmount | undefined;
                    maxFee?: import("@algorandfoundation/algokit-utils/types/amount").AlgoAmount | undefined;
                    validityWindow?: number | undefined;
                    firstValidRound?: bigint | undefined;
                    lastValidRound?: bigint | undefined;
                    appId: bigint;
                    onComplete?: OnApplicationComplete.UpdateApplicationOC | undefined;
                    args?: Uint8Array[] | undefined;
                    accountReferences?: string[] | undefined;
                    appReferences?: bigint[] | undefined;
                    assetReferences?: bigint[] | undefined;
                    boxReferences?: (import("@algorandfoundation/algokit-utils/types/app-manager").BoxReference | import("@algorandfoundation/algokit-utils/types/app-manager").BoxIdentifier)[] | undefined;
                    approvalProgram: string | Uint8Array;
                    clearStateProgram: string | Uint8Array;
                }> | undefined)[] | undefined;
            }>;
        };
        /**
         * Makes a clear_state call to an existing instance of the Council smart contract.
         *
         * @param params The params for the bare (raw) call
         * @returns The clearState result
         */
        clearState: (params?: Expand<AppClientBareCallParams>) => import("@algorandfoundation/algokit-utils/types/composer").AppCallParams;
        /**
         * Makes a call to the Council smart contract using the `add_member(address)void` ABI method.
         *
         * Add a member to the council.
         *
         * @param params The params for the smart contract call
         * @returns The call params
         */
        addMember: (params: CallParams<CouncilArgs['obj']['add_member(address)void'] | CouncilArgs['tuple']['add_member(address)void']> & {
            onComplete?: OnApplicationComplete.NoOpOC;
        }) => Promise<AppCallMethodCall>;
        /**
         * Makes a call to the Council smart contract using the `remove_member(address)void` ABI method.
         *
         * Remove a member from the council.
         *
         * @param params The params for the smart contract call
         * @returns The call params
         */
        removeMember: (params: CallParams<CouncilArgs['obj']['remove_member(address)void'] | CouncilArgs['tuple']['remove_member(address)void']> & {
            onComplete?: OnApplicationComplete.NoOpOC;
        }) => Promise<AppCallMethodCall>;
        /**
         * Makes a call to the Council smart contract using the `vote(uint64,bool)void` ABI method.
         *
         * Cast a vote on a proposal.
         *
         * @param params The params for the smart contract call
         * @returns The call params
         */
        vote: (params: CallParams<CouncilArgs['obj']['vote(uint64,bool)void'] | CouncilArgs['tuple']['vote(uint64,bool)void']> & {
            onComplete?: OnApplicationComplete.NoOpOC;
        }) => Promise<AppCallMethodCall>;
        /**
         * Makes a call to the Council smart contract using the `op_up()void` ABI method.
         *
         * @param params The params for the smart contract call
         * @returns The call params
         */
        opUp: (params?: CallParams<CouncilArgs['obj']['op_up()void'] | CouncilArgs['tuple']['op_up()void']> & {
            onComplete?: OnApplicationComplete.NoOpOC;
        }) => Promise<AppCallMethodCall>;
    };
    /**
     * Create transactions for the current app
     */
    readonly createTransaction: {
        /**
         * Gets available update methods
         */
        update: {
            /**
             * Updates an existing instance of the Council smart contract using the `update_council()void` ABI method.
             *
             * Update the council contract.
             *
             * @param params The params for the smart contract call
             * @returns The update transaction
             */
            updateCouncil: (params?: CallParams<CouncilArgs['obj']['update_council()void'] | CouncilArgs['tuple']['update_council()void']> & AppClientCompilationParams) => Promise<{
                transactions: Transaction[];
                methodCalls: Map<number, import("algosdk").ABIMethod>;
                signers: Map<number, TransactionSigner>;
            }>;
        };
        /**
         * Makes a clear_state call to an existing instance of the Council smart contract.
         *
         * @param params The params for the bare (raw) call
         * @returns The clearState result
         */
        clearState: (params?: Expand<AppClientBareCallParams>) => Promise<Transaction>;
        /**
         * Makes a call to the Council smart contract using the `add_member(address)void` ABI method.
         *
         * Add a member to the council.
         *
         * @param params The params for the smart contract call
         * @returns The call transaction
         */
        addMember: (params: CallParams<CouncilArgs['obj']['add_member(address)void'] | CouncilArgs['tuple']['add_member(address)void']> & {
            onComplete?: OnApplicationComplete.NoOpOC;
        }) => Promise<{
            transactions: Transaction[];
            methodCalls: Map<number, import("algosdk").ABIMethod>;
            signers: Map<number, TransactionSigner>;
        }>;
        /**
         * Makes a call to the Council smart contract using the `remove_member(address)void` ABI method.
         *
         * Remove a member from the council.
         *
         * @param params The params for the smart contract call
         * @returns The call transaction
         */
        removeMember: (params: CallParams<CouncilArgs['obj']['remove_member(address)void'] | CouncilArgs['tuple']['remove_member(address)void']> & {
            onComplete?: OnApplicationComplete.NoOpOC;
        }) => Promise<{
            transactions: Transaction[];
            methodCalls: Map<number, import("algosdk").ABIMethod>;
            signers: Map<number, TransactionSigner>;
        }>;
        /**
         * Makes a call to the Council smart contract using the `vote(uint64,bool)void` ABI method.
         *
         * Cast a vote on a proposal.
         *
         * @param params The params for the smart contract call
         * @returns The call transaction
         */
        vote: (params: CallParams<CouncilArgs['obj']['vote(uint64,bool)void'] | CouncilArgs['tuple']['vote(uint64,bool)void']> & {
            onComplete?: OnApplicationComplete.NoOpOC;
        }) => Promise<{
            transactions: Transaction[];
            methodCalls: Map<number, import("algosdk").ABIMethod>;
            signers: Map<number, TransactionSigner>;
        }>;
        /**
         * Makes a call to the Council smart contract using the `op_up()void` ABI method.
         *
         * @param params The params for the smart contract call
         * @returns The call transaction
         */
        opUp: (params?: CallParams<CouncilArgs['obj']['op_up()void'] | CouncilArgs['tuple']['op_up()void']> & {
            onComplete?: OnApplicationComplete.NoOpOC;
        }) => Promise<{
            transactions: Transaction[];
            methodCalls: Map<number, import("algosdk").ABIMethod>;
            signers: Map<number, TransactionSigner>;
        }>;
    };
    /**
     * Send calls to the current app
     */
    readonly send: {
        /**
         * Gets available update methods
         */
        update: {
            /**
             * Updates an existing instance of the Council smart contract using the `update_council()void` ABI method.
             *
             * Update the council contract.
             *
             * @param params The params for the smart contract call
             * @returns The update result
             */
            updateCouncil: (params?: CallParams<CouncilArgs['obj']['update_council()void'] | CouncilArgs['tuple']['update_council()void']> & AppClientCompilationParams & SendParams) => Promise<{
                return: void | undefined;
                compiledApproval?: import("@algorandfoundation/algokit-utils/types/app").CompiledTeal | undefined;
                compiledClear?: import("@algorandfoundation/algokit-utils/types/app").CompiledTeal | undefined;
                groupId: string;
                txIds: string[];
                returns?: ABIReturn[] | undefined;
                confirmations: modelsv2.PendingTransactionResponse[];
                transactions: Transaction[];
                confirmation: modelsv2.PendingTransactionResponse;
                transaction: Transaction;
            }>;
        };
        /**
         * Makes a clear_state call to an existing instance of the Council smart contract.
         *
         * @param params The params for the bare (raw) call
         * @returns The clearState result
         */
        clearState: (params?: Expand<AppClientBareCallParams & SendParams>) => Promise<{
            groupId: string;
            txIds: string[];
            returns?: ABIReturn[] | undefined;
            confirmations: modelsv2.PendingTransactionResponse[];
            transactions: Transaction[];
            confirmation: modelsv2.PendingTransactionResponse;
            transaction: Transaction;
            return?: ABIReturn | undefined;
        }>;
        /**
         * Makes a call to the Council smart contract using the `add_member(address)void` ABI method.
         *
         * Add a member to the council.
         *
         * @param params The params for the smart contract call
         * @returns The call result
         */
        addMember: (params: CallParams<CouncilArgs['obj']['add_member(address)void'] | CouncilArgs['tuple']['add_member(address)void']> & SendParams & {
            onComplete?: OnApplicationComplete.NoOpOC;
        }) => Promise<{
            return: void | undefined;
            returns?: ABIReturn[] | undefined;
            groupId: string;
            txIds: string[];
            confirmations: modelsv2.PendingTransactionResponse[];
            transactions: Transaction[];
            confirmation: modelsv2.PendingTransactionResponse;
            transaction: Transaction;
        }>;
        /**
         * Makes a call to the Council smart contract using the `remove_member(address)void` ABI method.
         *
         * Remove a member from the council.
         *
         * @param params The params for the smart contract call
         * @returns The call result
         */
        removeMember: (params: CallParams<CouncilArgs['obj']['remove_member(address)void'] | CouncilArgs['tuple']['remove_member(address)void']> & SendParams & {
            onComplete?: OnApplicationComplete.NoOpOC;
        }) => Promise<{
            return: void | undefined;
            returns?: ABIReturn[] | undefined;
            groupId: string;
            txIds: string[];
            confirmations: modelsv2.PendingTransactionResponse[];
            transactions: Transaction[];
            confirmation: modelsv2.PendingTransactionResponse;
            transaction: Transaction;
        }>;
        /**
         * Makes a call to the Council smart contract using the `vote(uint64,bool)void` ABI method.
         *
         * Cast a vote on a proposal.
         *
         * @param params The params for the smart contract call
         * @returns The call result
         */
        vote: (params: CallParams<CouncilArgs['obj']['vote(uint64,bool)void'] | CouncilArgs['tuple']['vote(uint64,bool)void']> & SendParams & {
            onComplete?: OnApplicationComplete.NoOpOC;
        }) => Promise<{
            return: void | undefined;
            returns?: ABIReturn[] | undefined;
            groupId: string;
            txIds: string[];
            confirmations: modelsv2.PendingTransactionResponse[];
            transactions: Transaction[];
            confirmation: modelsv2.PendingTransactionResponse;
            transaction: Transaction;
        }>;
        /**
         * Makes a call to the Council smart contract using the `op_up()void` ABI method.
         *
         * @param params The params for the smart contract call
         * @returns The call result
         */
        opUp: (params?: CallParams<CouncilArgs['obj']['op_up()void'] | CouncilArgs['tuple']['op_up()void']> & SendParams & {
            onComplete?: OnApplicationComplete.NoOpOC;
        }) => Promise<{
            return: void | undefined;
            returns?: ABIReturn[] | undefined;
            groupId: string;
            txIds: string[];
            confirmations: modelsv2.PendingTransactionResponse[];
            transactions: Transaction[];
            confirmation: modelsv2.PendingTransactionResponse;
            transaction: Transaction;
        }>;
    };
    /**
     * Clone this app client with different params
     *
     * @param params The params to use for the the cloned app client. Omit a param to keep the original value. Set a param to override the original value. Setting to undefined will clear the original value.
     * @returns A new app client with the altered params
     */
    clone(params: CloneAppClientParams): CouncilClient;
    /**
     * Methods to access state for the current Council app
     */
    state: {
        /**
         * Methods to access global state for the current Council app
         */
        global: {
            /**
             * Get all current keyed values from global state
             */
            getAll: () => Promise<Partial<Expand<GlobalKeysState>>>;
            /**
             * Get the current value of the registry_app_id key in global state
             */
            registryAppId: () => Promise<bigint | undefined>;
            /**
             * Get the current value of the member_count key in global state
             */
            memberCount: () => Promise<bigint | undefined>;
        };
        /**
         * Methods to access box state for the current Council app
         */
        box: {
            /**
             * Get all current keyed values from box state
             */
            getAll: () => Promise<Partial<Expand<BoxKeysState>>>;
            /**
             * Get values from the members map in box state
             */
            members: {
                /**
                 * Get all current values of the members map in box state
                 */
                getMap: () => Promise<Map<string, Uint8Array>>;
                /**
                 * Get a current value of the members map by key from box state
                 */
                value: (key: string) => Promise<Uint8Array | undefined>;
            };
            /**
             * Get values from the votes map in box state
             */
            votes: {
                /**
                 * Get all current values of the votes map in box state
                 */
                getMap: () => Promise<Map<bigint, [string, boolean][]>>;
                /**
                 * Get a current value of the votes map by key from box state
                 */
                value: (key: bigint | number) => Promise<[string, boolean][] | undefined>;
            };
        };
    };
    newGroup(): CouncilComposer;
}
export type CouncilComposer<TReturns extends [...any[]] = []> = {
    /**
     * Calls the add_member(address)void ABI method.
     *
     * Add a member to the council.
     *
     * @param args The arguments for the contract call
     * @param params Any additional parameters for the call
     * @returns The typed transaction composer so you can fluently chain multiple calls or call execute to execute all queued up transactions
     */
    addMember(params?: CallParams<CouncilArgs['obj']['add_member(address)void'] | CouncilArgs['tuple']['add_member(address)void']>): CouncilComposer<[...TReturns, CouncilReturns['add_member(address)void'] | undefined]>;
    /**
     * Calls the remove_member(address)void ABI method.
     *
     * Remove a member from the council.
     *
     * @param args The arguments for the contract call
     * @param params Any additional parameters for the call
     * @returns The typed transaction composer so you can fluently chain multiple calls or call execute to execute all queued up transactions
     */
    removeMember(params?: CallParams<CouncilArgs['obj']['remove_member(address)void'] | CouncilArgs['tuple']['remove_member(address)void']>): CouncilComposer<[...TReturns, CouncilReturns['remove_member(address)void'] | undefined]>;
    /**
     * Calls the vote(uint64,bool)void ABI method.
     *
     * Cast a vote on a proposal.
     *
     * @param args The arguments for the contract call
     * @param params Any additional parameters for the call
     * @returns The typed transaction composer so you can fluently chain multiple calls or call execute to execute all queued up transactions
     */
    vote(params?: CallParams<CouncilArgs['obj']['vote(uint64,bool)void'] | CouncilArgs['tuple']['vote(uint64,bool)void']>): CouncilComposer<[...TReturns, CouncilReturns['vote(uint64,bool)void'] | undefined]>;
    /**
     * Calls the op_up()void ABI method.
     *
     * @param args The arguments for the contract call
     * @param params Any additional parameters for the call
     * @returns The typed transaction composer so you can fluently chain multiple calls or call execute to execute all queued up transactions
     */
    opUp(params?: CallParams<CouncilArgs['obj']['op_up()void'] | CouncilArgs['tuple']['op_up()void']>): CouncilComposer<[...TReturns, CouncilReturns['op_up()void'] | undefined]>;
    /**
     * Gets available update methods
     */
    readonly update: {
        /**
         * Updates an existing instance of the Council smart contract using the update_council()void ABI method.
         *
         * @param args The arguments for the smart contract call
         * @param params Any additional parameters for the call
         * @returns The typed transaction composer so you can fluently chain multiple calls or call execute to execute all queued up transactions
         */
        updateCouncil(params?: CallParams<CouncilArgs['obj']['update_council()void'] | CouncilArgs['tuple']['update_council()void']>): CouncilComposer<[...TReturns, CouncilReturns['update_council()void'] | undefined]>;
    };
    /**
     * Makes a clear_state call to an existing instance of the Council smart contract.
     *
     * @param args The arguments for the bare call
     * @returns The typed transaction composer so you can fluently chain multiple calls or call execute to execute all queued up transactions
     */
    clearState(params?: AppClientBareCallParams): CouncilComposer<[...TReturns, undefined]>;
    /**
     * Adds a transaction to the composer
     *
     * @param txn A transaction to add to the transaction group
     * @param signer The optional signer to use when signing this transaction.
     */
    addTransaction(txn: Transaction, signer?: TransactionSigner): CouncilComposer<TReturns>;
    /**
     * Returns the underlying AtomicTransactionComposer instance
     */
    composer(): Promise<TransactionComposer>;
    /**
     * Simulates the transaction group and returns the result
     */
    simulate(): Promise<CouncilComposerResults<TReturns> & {
        simulateResponse: SimulateResponse;
    }>;
    simulate(options: SkipSignaturesSimulateOptions): Promise<CouncilComposerResults<TReturns> & {
        simulateResponse: SimulateResponse;
    }>;
    simulate(options: RawSimulateOptions): Promise<CouncilComposerResults<TReturns> & {
        simulateResponse: SimulateResponse;
    }>;
    /**
     * Sends the transaction group to the network and returns the results
     */
    send(params?: SendParams): Promise<CouncilComposerResults<TReturns>>;
};
export type CouncilComposerResults<TReturns extends [...any[]]> = Expand<SendAtomicTransactionComposerResults & {
    returns: TReturns;
}>;
